# flake8: noqa: B950
# fmt: off
# This file was generated by AutoHeuristic. Do not modify it manually!
# To regenerate this file, take a look at the steps in the README.md file inside torchgen/_autoheuristic/async_tp/
from typing import Optional

from torch._inductor.autoheuristic.autoheuristic_utils import (
    AHContext,
    AHMetadata,
    Choice,
)
from torch._inductor.autoheuristic.learnedheuristic_interface import (
    LearnedHeuristicDecision,
)


class AsyncTPFuseH100(LearnedHeuristicDecision):

    def __init__(self) -> None:
        self.choices: list[Choice] = []
        self.fill_choices()

    def check_precondition(self, metadata: AHMetadata, context: AHContext,) -> bool:
        return (
            metadata.name == self.get_name()
            and metadata.shared_memory == 232448
            and str(metadata.device_capa) == "(9, 0)"
        )

    def get_confidence_threshold(self) -> float:
        return 0.8333333333333334

    def get_choice(self, idx: int) -> Optional[str]:
        if idx < len(self.choices):
            return self.choices[idx]
        return None

    def fill_choices(self) -> None:
        self.choices.append('fuse')
        self.choices.append('no_fuse')

    def get_name(self) -> str:
        return 'async_tp_fuse'

    def get_best_choices(self, context: AHContext) -> Optional[list[tuple[float, int]]]:
        if context.get_value('m_times_n') <= 14155776.0:
            if context.get_value('n') <= 9600.0:
                if context.get_value('m_times_k') <= 25952256.0:
                    return [(0.950, 1), (0.050, 0)]
                else:
                    return [(1.000, 0)]
            else:
                if context.get_value('k') <= 34816.0:
                    return None
                else:
                    return [(0.833, 1), (0.167, 0)]
        else:
            if context.get_value('m_times_n') <= 402653184.0:
                return [(1.000, 0)]
            else:
                return [(1.000, 1)]
