#!/usr/bin/env python3

import argparse
import json
import sys


EXPECTED_CONTRACT_NAME = "ChannelCatContract"
EXPECTED_FAMILY = "Rank4Dim1BufferView"


def _require(condition, message):
    if not condition:
        raise RuntimeError(message)


def _cpp_string(value):
    return json.dumps(value)


def _cpp_bool(value):
    return "true" if value else "false"


def _load_spec(path):
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def _validate_channel_cat_spec(spec):
    _require(
        spec.get("contract_name") == EXPECTED_CONTRACT_NAME,
        "expected ChannelCatContract spec",
    )
    _require(
        spec.get("family") == EXPECTED_FAMILY,
        "expected Rank4Dim1BufferView family",
    )
    bounds = spec.get("bounds")
    _require(isinstance(bounds, dict), "spec bounds must be an object")
    _require(bounds.get("channels", {}).get("min") is not None, "missing channel min")
    _require(
        bounds.get("channels", {}).get("max_per_input") is not None,
        "missing per-input channel max",
    )
    _require(
        bounds.get("channels", {}).get("multiple_of") is not None,
        "missing channel multiple",
    )
    _require(
        bounds.get("channels", {}).get("max_total") is not None,
        "missing total channel max",
    )
    for key in ("input_count", "height", "width"):
        _require(bounds.get(key, {}).get("min") is not None, f"missing {key} min")
        _require(bounds.get(key, {}).get("max") is not None, f"missing {key} max")


def generate_channel_cat_header(spec, source_name):
    _validate_channel_cat_spec(spec)
    bounds = spec["bounds"]
    channels = bounds["channels"]

    lines = [
        "// Generated by tools/vulkan_contracts/gen_contract_spec_cpp.py",
        f"// Source: {source_name}",
        "// Do not edit by hand.",
        "",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace at {",
        "namespace native {",
        "namespace vulkan {",
        "namespace ops {",
        "namespace utils {",
        "namespace generated {",
        "",
        f"constexpr const char* kChannelCatContractName = {_cpp_string(spec['contract_name'])};",
        (
            "constexpr const char* kChannelCatRank4Dim1BufferViewFamilyName = "
            f"{_cpp_string(spec['family'])};"
        ),
        (
            "constexpr const char* kChannelCatRank4Dim1BufferViewTupleId = "
            f"{_cpp_string(spec['tuple_id'])};"
        ),
        (
            "constexpr const char* kChannelCatRank4Dim1BufferViewWriterOp = "
            f"{_cpp_string(spec['writer_op'])};"
        ),
        (
            "constexpr const char* kChannelCatRank4Dim1BufferViewRouteLabel = "
            f"{_cpp_string(spec['route_label'])};"
        ),
        "",
        (
            "constexpr std::int64_t kChannelCatRank4Dim1MinInputs = "
            f"{bounds['input_count']['min']};"
        ),
        (
            "constexpr std::int64_t kChannelCatRank4Dim1MaxInputs = "
            f"{bounds['input_count']['max']};"
        ),
        f"constexpr std::int64_t kChannelCatRank4Dim1Rank = {bounds['rank']};",
        f"constexpr std::int64_t kChannelCatRank4Dim1Dim = {bounds['dim']};",
        f"constexpr std::int64_t kChannelCatRank4Dim1Batch = {bounds['batch']};",
        (
            "constexpr std::int64_t kChannelCatRank4Dim1MinInputChannels = "
            f"{channels['min']};"
        ),
        (
            "constexpr std::int64_t kChannelCatRank4Dim1MaxInputChannels = "
            f"{channels['max_per_input']};"
        ),
        (
            "constexpr std::int64_t kChannelCatRank4Dim1ChannelMultiple = "
            f"{channels['multiple_of']};"
        ),
        (
            "constexpr std::int64_t kChannelCatRank4Dim1MaxTotalChannels = "
            f"{channels['max_total']};"
        ),
        (
            "constexpr std::int64_t kChannelCatRank4Dim1MinHeight = "
            f"{bounds['height']['min']};"
        ),
        (
            "constexpr std::int64_t kChannelCatRank4Dim1MaxHeight = "
            f"{bounds['height']['max']};"
        ),
        (
            "constexpr std::int64_t kChannelCatRank4Dim1MinWidth = "
            f"{bounds['width']['min']};"
        ),
        (
            "constexpr std::int64_t kChannelCatRank4Dim1MaxWidth = "
            f"{bounds['width']['max']};"
        ),
        (
            "constexpr bool kChannelCatRank4Dim1RequiresVulkan = "
            f"{_cpp_bool(bounds['requires_vulkan'])};"
        ),
        (
            "constexpr bool kChannelCatRank4Dim1RequiresContiguous = "
            f"{_cpp_bool(bounds['requires_contiguous'])};"
        ),
        (
            "constexpr bool kChannelCatRank4Dim1RequiresBufferStorage = "
            f"{_cpp_bool(bounds['requires_buffer_storage'])};"
        ),
        (
            "constexpr bool kChannelCatRank4Dim1RequiresBufferCompute = "
            f"{_cpp_bool(bounds['requires_buffer_compute'])};"
        ),
        "",
        "} // namespace generated",
        "} // namespace utils",
        "} // namespace ops",
        "} // namespace vulkan",
        "} // namespace native",
        "} // namespace at",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--spec", required=True)
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()

    spec = _load_spec(args.spec)
    output = generate_channel_cat_header(spec, args.spec.replace("\\", "/"))
    if args.stdout:
        sys.stdout.buffer.write(output.encode("utf-8"))
        return
    raise RuntimeError("only --stdout is supported for the MVP generator")


if __name__ == "__main__":
    main()
