#include <ATen/native/vulkan/api/Env.h>

#include <cstring>
#include <iterator>

namespace at::native::vulkan::api {
namespace {

constexpr VulkanEnvFlagSpec kAllowedVulkanEnvFlags[] = {
    {"PYTORCH_VULKAN_ALLOC_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose allocator behavior",
     "diagnostic log tests and manual debugging"},
    {"PYTORCH_VULKAN_CHECK_FINITE_AFTER_WRITE",
     VulkanEnvFlagKind::CorrectnessDiagnostic,
     "detect non-finite tensor writes while debugging kernels",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_COMPILED_SESSION_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose compiled-session capture and replay",
     "compiled-session C++ tests"},
    {"PYTORCH_VULKAN_CONV_CACHE_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose convolution packed-weight cache behavior",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_COPY_SYNC_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose explicit copy/readback synchronization",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_CPU_FALLBACK",
     VulkanEnvFlagKind::ActiveImplementationGate,
     "select CPU fallback policy for unsupported ops",
     "fallback policy tests"},
    {"PYTORCH_VULKAN_CPU_TIMELINE_LOG",
     VulkanEnvFlagKind::Profiling,
     "record per-operation CPU timeline events",
     "manual profiling"},
    {"PYTORCH_VULKAN_CPU_TIMELINE_SUMMARY_LOG",
     VulkanEnvFlagKind::Profiling,
     "record aggregated CPU timeline counters",
     "manual profiling"},
    {"PYTORCH_VULKAN_CAPABILITY_PROFILE",
     VulkanEnvFlagKind::HardwareCapabilityGate,
     "mask runtime planner capabilities for reduced-envelope tests",
     "capability profile governance and runtime-policy tests"},
    {"PYTORCH_VULKAN_EXECUTION_OBJECT_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose execution object cache behavior",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_EXECUTION_PLAN_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose execution planning decisions",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_EXECUTION_PROGRAM_CACHE_MB",
     VulkanEnvFlagKind::CacheLimit,
     "bound execution-program cache memory",
     "program cache tests and manual stress"},
    {"PYTORCH_VULKAN_EXECUTION_PROGRAM_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose execution-program cache behavior",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_FAIL_ON_SYNC_READBACK",
     VulkanEnvFlagKind::CorrectnessDiagnostic,
     "force blocking readbacks to fail in tests",
     "fallback policy tests"},
    {"PYTORCH_VULKAN_FAILURE_LOG",
     VulkanEnvFlagKind::Logging,
     "capture structured Vulkan failure diagnostics",
     "C++ guard and route-policy tests"},
    {"PYTORCH_VULKAN_GPU_TIMESTAMP_LOG",
     VulkanEnvFlagKind::Profiling,
     "record GPU timestamp query results",
     "querypool tests and manual profiling"},
    {"PYTORCH_VULKAN_INFERENCE_GRAPH_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose inference graph build and replay",
     "inference graph C++ tests"},
    {"PYTORCH_VULKAN_LINEAR_CACHE_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose linear packed-context cache behavior",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_LOG_CPU_FALLBACK",
     VulkanEnvFlagKind::Logging,
     "diagnose unsupported op CPU fallback",
     "fallback policy tests"},
    {"PYTORCH_VULKAN_LOG_FALLBACK",
     VulkanEnvFlagKind::Logging,
     "diagnose fallback behavior",
     "fallback policy tests"},
    {"PYTORCH_VULKAN_LOG_SYNC_READBACK",
     VulkanEnvFlagKind::Logging,
     "diagnose blocking readbacks",
     "fallback policy tests"},
    {"PYTORCH_VULKAN_MATERIALIZE_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose layout/materialization transitions",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_NO_CPU_FALLBACK",
     VulkanEnvFlagKind::CorrectnessDiagnostic,
     "force unsupported ops to fail in tests",
     "fallback policy tests"},
    {"PYTORCH_VULKAN_OP_HIT_LOG",
     VulkanEnvFlagKind::Logging,
     "record Vulkan op dispatch hits",
     "C++ op-hit tests"},
    {"PYTORCH_VULKAN_PACKED_WEIGHT_CACHE_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose packed-weight cache behavior",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_REPLAY_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose replay tensor state",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_ROUTE_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose route-policy decisions",
     "route-policy tests"},
    {"PYTORCH_VULKAN_RUNTIME_POLICY_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose runtime policy decisions",
     "runtime policy C++ tests"},
    {"PYTORCH_VULKAN_SDPA_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose SDPA route and kernel selection",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_SYNC_LOG",
     VulkanEnvFlagKind::Logging,
     "report synchronization counters",
     "sync counter tests and manual diagnostics"},
    {"PYTORCH_VULKAN_TENSOR_STATE_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose tensor representation transitions",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_TRANSITION_LOG",
     VulkanEnvFlagKind::Logging,
     "diagnose transition and materialization decisions",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_VALIDATE_TENSOR_STATE",
     VulkanEnvFlagKind::CorrectnessDiagnostic,
     "validate tensor state invariants",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_VALIDATE_VALUES",
     VulkanEnvFlagKind::CorrectnessDiagnostic,
     "validate tensor values across Vulkan paths",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_VALUE_TRACE",
     VulkanEnvFlagKind::CorrectnessDiagnostic,
     "trace values for accuracy debugging",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_VALUE_TRACE_LOG",
     VulkanEnvFlagKind::Logging,
     "write value trace diagnostics",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_VALUE_TRACE_MAX_ABS",
     VulkanEnvFlagKind::CorrectnessDiagnostic,
     "configure value trace threshold",
     "manual diagnostics"},
    {"PYTORCH_VULKAN_VALUE_TRACE_SAMPLES",
     VulkanEnvFlagKind::CorrectnessDiagnostic,
     "configure value trace sample count",
     "manual diagnostics"},
};

} // namespace

const VulkanEnvFlagSpec* registered_vulkan_env_flags(size_t* count) {
  if (count) {
    *count = std::size(kAllowedVulkanEnvFlags);
  }
  return kAllowedVulkanEnvFlags;
}

const VulkanEnvFlagSpec* find_vulkan_env_flag(const char* name) {
  if (!name) {
    return nullptr;
  }
  for (const auto& spec : kAllowedVulkanEnvFlags) {
    if (std::strcmp(spec.name, name) == 0) {
      return &spec;
    }
  }
  return nullptr;
}

} // namespace at::native::vulkan::api
